-- Consulte — seed inicial
-- Rodar depois de supabase/schema.sql.
-- Cobre: corretora Ariádne, cidades, especialidades comuns e dicionário de sinônimos leigos.
-- A lista de especialidades/sinônimos deve ser revisada e completada contra os valores reais
-- da planilha quando ela chegar (ver scripts/importar-planilha.ts) — isso aqui é o ponto de partida.

insert into corretoras (nome, slug, operadora_padrao)
values ('Ariádne', 'ariadne', 'Amil');

insert into cidades (nome, uf) values
  ('Itabirito', 'MG'),
  ('Sete Lagoas', 'MG');

-- Especialidades
insert into especialidades (nome_normalizado) values
  ('Clínica Médica'),
  ('Pediatria'),
  ('Ginecologia e Obstetrícia'),
  ('Cardiologia'),
  ('Dermatologia'),
  ('Ortopedia e Traumatologia'),
  ('Oftalmologia'),
  ('Otorrinolaringologia'),
  ('Psiquiatria'),
  ('Neurologia'),
  ('Urologia'),
  ('Endocrinologia'),
  ('Gastroenterologia'),
  ('Nefrologia'),
  ('Pneumologia'),
  ('Reumatologia'),
  ('Cirurgia Geral'),
  ('Cirurgia Vascular'),
  ('Cirurgia Plástica'),
  ('Cirurgia Torácica'),
  ('Cirurgia Pediátrica'),
  ('Angiologia'),
  ('Hematologia'),
  ('Infectologia'),
  ('Oncologia'),
  ('Mastologia'),
  ('Geriatria'),
  ('Anestesiologia'),
  ('Radiologia'),
  ('Medicina do Trabalho'),
  ('Medicina de Família e Comunidade'),
  ('Fisiatria'),
  ('Nutrologia'),
  ('Homeopatia'),
  ('Alergologia e Imunologia'),
  ('Coloproctologia'),
  ('Neurocirurgia'),
  ('Cirurgia de Cabeça e Pescoço'),
  ('Endoscopia'),
  ('Medicina Intensiva'),
  ('Patologia');

-- Sinônimos (termo em minúsculo, sem acento — normalização é feita na busca)
with esp as (select id, nome_normalizado from especialidades)
insert into especialidade_sinonimos (especialidade_id, termo)
select esp.id, s.termo
from (values
  ('Clínica Médica', 'clinico geral'),
  ('Clínica Médica', 'clinica geral'),
  ('Clínica Médica', 'medico de familia'),
  ('Clínica Médica', 'checape'),
  ('Clínica Médica', 'checkup'),
  ('Pediatria', 'pediatra'),
  ('Pediatria', 'crianca'),
  ('Pediatria', 'medico de crianca'),
  ('Pediatria', 'medico infantil'),
  ('Ginecologia e Obstetrícia', 'ginecologista'),
  ('Ginecologia e Obstetrícia', 'ginecologia'),
  ('Ginecologia e Obstetrícia', 'obstetra'),
  ('Ginecologia e Obstetrícia', 'pre natal'),
  ('Ginecologia e Obstetrícia', 'gravidez'),
  ('Ginecologia e Obstetrícia', 'medico da mulher'),
  ('Cardiologia', 'cardiologista'),
  ('Cardiologia', 'coracao'),
  ('Cardiologia', 'medico do coracao'),
  ('Dermatologia', 'dermatologista'),
  ('Dermatologia', 'pele'),
  ('Dermatologia', 'medico de pele'),
  ('Dermatologia', 'espinha'),
  ('Dermatologia', 'acne'),
  ('Ortopedia e Traumatologia', 'ortopedista'),
  ('Ortopedia e Traumatologia', 'ortopedia'),
  ('Ortopedia e Traumatologia', 'osso'),
  ('Ortopedia e Traumatologia', 'fratura'),
  ('Ortopedia e Traumatologia', 'coluna'),
  ('Ortopedia e Traumatologia', 'joelho'),
  ('Oftalmologia', 'oftalmologista'),
  ('Oftalmologia', 'oftalmo'),
  ('Oftalmologia', 'olhos'),
  ('Oftalmologia', 'medico dos olhos'),
  ('Oftalmologia', 'vista'),
  ('Otorrinolaringologia', 'otorrino'),
  ('Otorrinolaringologia', 'ouvido'),
  ('Otorrinolaringologia', 'garganta'),
  ('Otorrinolaringologia', 'nariz'),
  ('Otorrinolaringologia', 'sinusite'),
  ('Psiquiatria', 'psiquiatra'),
  ('Psiquiatria', 'saude mental'),
  ('Psiquiatria', 'depressao'),
  ('Psiquiatria', 'ansiedade'),
  ('Neurologia', 'neurologista'),
  ('Neurologia', 'nervo'),
  ('Neurologia', 'dor de cabeca'),
  ('Neurologia', 'enxaqueca'),
  ('Neurologia', 'convulsao'),
  ('Urologia', 'urologista'),
  ('Urologia', 'prostata'),
  ('Urologia', 'rim e bexiga'),
  ('Urologia', 'medico do homem'),
  ('Endocrinologia', 'endocrinologista'),
  ('Endocrinologia', 'diabetes'),
  ('Endocrinologia', 'tireoide'),
  ('Endocrinologia', 'hormonio'),
  ('Gastroenterologia', 'gastro'),
  ('Gastroenterologia', 'gastroenterologista'),
  ('Gastroenterologia', 'estomago'),
  ('Gastroenterologia', 'intestino'),
  ('Gastroenterologia', 'figado'),
  ('Nefrologia', 'nefrologista'),
  ('Nefrologia', 'rim'),
  ('Nefrologia', 'rins'),
  ('Pneumologia', 'pneumologista'),
  ('Pneumologia', 'pulmao'),
  ('Pneumologia', 'asma'),
  ('Pneumologia', 'bronquite'),
  ('Reumatologia', 'reumatologista'),
  ('Reumatologia', 'reumatismo'),
  ('Reumatologia', 'artrite'),
  ('Reumatologia', 'dor nas juntas'),
  ('Cirurgia Geral', 'cirurgiao geral'),
  ('Cirurgia Geral', 'cirurgia'),
  ('Cirurgia Vascular', 'cirurgiao vascular'),
  ('Cirurgia Vascular', 'varizes'),
  ('Cirurgia Vascular', 'vasos'),
  ('Cirurgia Plástica', 'cirurgiao plastico'),
  ('Cirurgia Plástica', 'plastica'),
  ('Angiologia', 'angiologista'),
  ('Angiologia', 'circulacao'),
  ('Hematologia', 'hematologista'),
  ('Hematologia', 'sangue'),
  ('Hematologia', 'anemia'),
  ('Infectologia', 'infectologista'),
  ('Infectologia', 'infeccao'),
  ('Oncologia', 'oncologista'),
  ('Oncologia', 'cancer'),
  ('Mastologia', 'mastologista'),
  ('Mastologia', 'mama'),
  ('Mastologia', 'seio'),
  ('Geriatria', 'geriatra'),
  ('Geriatria', 'idoso'),
  ('Geriatria', 'medico de idoso'),
  ('Nutrologia', 'nutrologo'),
  ('Nutrologia', 'nutricao'),
  ('Nutrologia', 'emagrecimento'),
  ('Alergologia e Imunologia', 'alergista'),
  ('Alergologia e Imunologia', 'alergia'),
  ('Alergologia e Imunologia', 'rinite'),
  ('Coloproctologia', 'proctologista'),
  ('Coloproctologia', 'hemorroida'),
  ('Coloproctologia', 'intestino grosso'),
  ('Neurocirurgia', 'neurocirurgiao'),
  ('Neurocirurgia', 'cirurgia de cabeca'),
  ('Cirurgia de Cabeça e Pescoço', 'cirurgia de cabeca e pescoco'),
  ('Medicina do Trabalho', 'medico do trabalho'),
  ('Medicina do Trabalho', 'exame admissional'),
  ('Medicina do Trabalho', 'exame demissional'),
  ('Fisiatria', 'fisiatra'),
  ('Fisiatria', 'reabilitacao')
) as s(nome_normalizado, termo)
join esp on esp.nome_normalizado = s.nome_normalizado;

-- Especialidades odontológicas (as 15 categorias da rede credenciada Amil) --------
insert into especialidades (nome_normalizado, tipo) values
  ('Clínica Geral', 'dentista'),
  ('Cirurgia', 'dentista'),
  ('Endodontia', 'dentista'),
  ('Prótese Dentária', 'dentista'),
  ('Odontologia Estética', 'dentista'),
  ('Ortodontia', 'dentista'),
  ('Periodontia', 'dentista'),
  ('Implantodontia', 'dentista'),
  ('Odontopediatria', 'dentista'),
  ('Odontogeriatria', 'dentista'),
  ('Estomatologia', 'dentista'),
  ('Radiologia Odontológica e Imaginologia', 'dentista'),
  ('Disfunção Temporomandibular e Dor Orofacial', 'dentista'),
  ('Odontologia para Pacientes com Necessidades Especiais', 'dentista'),
  ('Urgência em Consultório Agendada', 'dentista')
on conflict (nome_normalizado) do nothing;

-- Sinônimos leigos das especialidades odontológicas -----------------------------
with esp as (select id, nome_normalizado from especialidades where tipo = 'dentista')
insert into especialidade_sinonimos (especialidade_id, termo)
select esp.id, s.termo
from (values
  ('Endodontia', 'canal'),
  ('Endodontia', 'tratamento de canal'),
  ('Endodontia', 'dor no dente'),
  ('Ortodontia', 'aparelho'),
  ('Ortodontia', 'aparelho nos dentes'),
  ('Ortodontia', 'aparelho dentario'),
  ('Ortodontia', 'dente torto'),
  ('Implantodontia', 'implante'),
  ('Implantodontia', 'implante dentario'),
  ('Prótese Dentária', 'protese'),
  ('Prótese Dentária', 'protese dentaria'),
  ('Prótese Dentária', 'dentadura'),
  ('Prótese Dentária', 'ponte movel'),
  ('Prótese Dentária', 'dente postico'),
  ('Periodontia', 'gengiva'),
  ('Periodontia', 'sangramento na gengiva'),
  ('Periodontia', 'limpeza'),
  ('Periodontia', 'tartaro'),
  ('Odontologia Estética', 'clareamento'),
  ('Odontologia Estética', 'clareamento dental'),
  ('Odontologia Estética', 'lente de contato dental'),
  ('Odontologia Estética', 'faceta'),
  ('Cirurgia', 'extracao'),
  ('Cirurgia', 'extracao de dente'),
  ('Cirurgia', 'arrancar dente'),
  ('Cirurgia', 'siso'),
  ('Cirurgia', 'dente do siso'),
  ('Odontopediatria', 'dentista de crianca'),
  ('Odontopediatria', 'dentista infantil'),
  ('Radiologia Odontológica e Imaginologia', 'raio x do dente'),
  ('Radiologia Odontológica e Imaginologia', 'radiografia odontologica'),
  ('Radiologia Odontológica e Imaginologia', 'panoramica'),
  ('Clínica Geral', 'dentista'),
  ('Clínica Geral', 'dentista clinico geral'),
  ('Clínica Geral', 'carie'),
  ('Clínica Geral', 'obturacao'),
  ('Clínica Geral', 'restauracao'),
  ('Estomatologia', 'lesao na boca'),
  ('Estomatologia', 'ferida na boca'),
  ('Disfunção Temporomandibular e Dor Orofacial', 'dtm'),
  ('Disfunção Temporomandibular e Dor Orofacial', 'dor na mandibula'),
  ('Disfunção Temporomandibular e Dor Orofacial', 'bruxismo'),
  ('Disfunção Temporomandibular e Dor Orofacial', 'range os dentes')
) as s(nome_normalizado, termo)
join esp on esp.nome_normalizado = s.nome_normalizado
on conflict (termo) do nothing;
